# vim: set tabstop=2 softtabstop=2 shiftwidth=2 expandtab:

name: trigger that java dll error
on:
  push:
  pull_request:
  workflow_call:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Run tests (${{ matrix.os }}, ${{ matrix.env }})
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      fail-fast: false
      matrix:
        os: 
          - macos-latest
        env:
          - ci/python_312.yaml
        jdk_from:
          - conda-forge
          - system

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.1

      - name: Install JVM (system-wide)
        if: ${{ matrix.jdk_from == 'system' }}
        uses: actions/setup-java@v4
        with: 
          distribution: temurin
          java-version: 21

      - name: Setup Conda
        uses: conda-incubator/setup-miniconda@v2.2.0
        with:
          activate-environment: r5py
          channel-priority: strict
          channels: conda-forge
          environment-file: ${{ matrix.env }}
          miniforge-variant: Mambaforge
          miniforge-version: latest
          use-mamba: true

      - name: Install JVM (from conda-forge)
        if: ${{ matrix.jdk_from == 'conda-forge' }}
        run: conda install 'openjdk>=21'

      - name: Install ourselves
        run: python -m pip install .[tests]

      - name: Run the thing
        run: python -c 'import foobar'
