# vim: set tabstop=2 softtabstop=2 shiftwidth=2 expandtab:

name: Trigger that Java library error
on:
  push:
  pull_request:
  workflow_call:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Trigger error
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with: 
          distribution: temurin
          java-version: 21

    #   - uses: actions/setup-python@v5
    #     with: 
    #       python-version: 3.12

      - run: curl -LO https://github.com/r5py/r5/releases/download/v7.0-r5py/r5-v7.0-r5py-all.jar

      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: test-setup-java-action
          environment-file: env.yml
          channel-priority: strict
          channels: conda-forge
          miniforge-variant: Mambaforge
          miniforge-version: latest
          use-mamba: true


      - run: pip install --upgrade jpype1

      - run: python try-to-start-jvm.py
