# vim: set tabstop=2 softtabstop=2 shiftwidth=2 expandtab:

name: Trigger that Java library error
on:
  push:
  pull_request:
  workflow_call:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Trigger error
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with: 
          distribution: temurin
          java-version: 21

      - uses: actions/setup-python@v5
        with: 
          python-version: 3.12

      - run: pip install --upgrade jpype1

      -  run: python -c 'import jpype; jpype.start_jvm()'
